import {cc, ptr} from 'bun:ffi';
import * as child_process from 'node:child_process';
import * as fs from 'node:fs';
import * as util from 'node:util';
import source from './rapidhash.c' with {type: 'file'};

type RapidhashFunc = (message: Buffer, len: number, seed: bigint) => bigint;

function compile(behaviour: 'fast' | 'protected'): [RapidhashFunc, bigint] {
  const result = cc({
    source,
    symbols: {
      _rapidhash_withSeed: {
        args: ['ptr', 'u32', 'u64'],
        returns: 'u64',
      },
      default_seed: {
        args: [],
        returns: 'u64',
      },
    },
    define: behaviour === 'fast' ? {} : {RAPIDHASH_PROTECTED: '1'},
  });

  const rapidhash: RapidhashFunc = (message, len, seed) => result.symbols._rapidhash_withSeed(ptr(message), len, seed);

  return [rapidhash, result.symbols.default_seed()];
}

function generateTestVectors1(rapidhash: RapidhashFunc, seeds: bigint[]): (readonly [string, bigint, bigint])[] {
  const testMessages = [
    '',
    'a',
    'AB',
    '123',
    '¶', // 2 bytes in UTF-8
    'あ', // 3 bytes in UTF-8
    'Hello, world.',
    'こんにちは、世界。',
  ];

  return seeds.flatMap((seed) =>
    testMessages
      .map((message) => [message, Buffer.from(message)] as const)
      .map(([message, buf]) => [message, seed, rapidhash(buf, buf.length, seed)] as const),
  );
}

function generateTestVectors2(rapidhash: RapidhashFunc, seeds: bigint[]) {
  const _testLongMessage =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';
  const testLongMessage = _testLongMessage.repeat(Math.ceil((2 ** 13 + 1) / _testLongMessage.length));
  const buffer = Buffer.from(testLongMessage);
  const result: (readonly [number, bigint, bigint])[] = [];

  for (let i = 1; i < buffer.length; i++) {
    if (i % 10000 === 0) {
      console.log(`${i} / ${buffer.length}`);
    }

    result.push(...seeds.map((seed) => [i, seed, rapidhash(buffer, i, seed)] as const));
  }

  return {longMessage: testLongMessage, testVectors: result};
}

function generateTestVectors(behaviour: 'fast' | 'protected', revision: string) {
  const [rapidhash, defaultSeed] = compile(behaviour);

  const seeds: bigint[] = [defaultSeed, 0n, 0x0123456789abcdefn, 0xfedcba9876543210n];

  const testVectors1 = generateTestVectors1(rapidhash, seeds);

  const {longMessage, testVectors: testVectors2} = generateTestVectors2(rapidhash, [defaultSeed]);

  const writeStream = fs.createWriteStream(`generated/test_vector_${behaviour}.ts`);

  writeStream.write('/* eslint-disable */\n');
  writeStream.write('// This file is generated by packages/gen-test/\n');
  writeStream.write(`// rapidhash revision: ${revision}\n`);

  writeStream.write('export const testVectors1: [string, bigint, bigint][] = ');
  writeStream.write(util.inspect(testVectors1, {depth: null, maxArrayLength: Number.POSITIVE_INFINITY}));
  writeStream.write(';\n\n');

  writeStream.write("export const longMessage = '");
  writeStream.write(longMessage);
  writeStream.write("';\n\n");

  writeStream.write('export const testVectors2: [number, bigint, bigint][] = ');
  writeStream.write(util.inspect(testVectors2, {depth: null, maxArrayLength: Number.POSITIVE_INFINITY}));
  writeStream.write(';\n');

  writeStream.end();
}

function main() {
  const revision = child_process.execSync("git -C src/rapidhash show --format='%H' --no-patch").toString().trim();

  generateTestVectors('fast', revision);
  generateTestVectors('protected', revision);
}

main();
