import * as fs from 'node:fs';
import * as path from 'node:path';
import * as util from 'node:util';
import type {Behaviour, FunctionName, TestVectors} from './types';

export class TestVectorWriter {
  readonly #destinationDir: string;
  readonly #version: string;
  readonly #functionName: FunctionName;
  readonly #behaviour: Behaviour;
  readonly #tag: string;
  readonly #revision: string;
  #writeStream: fs.WriteStream | undefined;

  constructor(args: {
    destinationDir: string;
    version: string;
    functionName: FunctionName;
    behaviour: Behaviour;
    tag: string;
    revision: string;
  }) {
    this.#destinationDir = args.destinationDir;
    this.#version = args.version;
    this.#functionName = args.functionName;
    this.#behaviour = args.behaviour;
    this.#tag = args.tag;
    this.#revision = args.revision;
  }

  createFile(): void {
    this.#writeStream = fs.createWriteStream(this.#filepath());
    this.#write(this.#header());
  }

  close(): void {
    this.#writeStream?.close();
  }

  writeTestVectors(testVectors: TestVectors): void {
    const varName = `testVectors_${this.#version.replaceAll('.', '_')}_${this.#functionName}_${this.#behaviour}`;
    const declaration = [
      `export const ${varName}: {`,
      '  short: {',
      '    testVectors: [string, bigint, bigint][]',
      '  },',
      '  long: {',
      '    message: string,',
      '    repetitions: number,',
      '    testVectors: [number, bigint, bigint][]',
      '  }',
      '} = ',
    ].join('\n');

    this.#write(declaration);
    this.#write(util.inspect(testVectors, {depth: null, maxArrayLength: Number.POSITIVE_INFINITY}));
    this.#write(';\n\n');
  }

  #filepath(): string {
    const filename = ['test_vector', this.#version, this.#functionName, this.#behaviour].join('_');
    return path.join(this.#destinationDir, `${filename}.ts`);
  }

  #write(data: string): void {
    this.#writeStream?.write(data);
  }

  #header(): string {
    return [
      '// This file is generated by packages/gen-test/',
      `// Git tag: ${this.#tag}, revision: ${this.#revision}`,
      '',
    ].join('\n');
  }
}
