name: Benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      - run: npm -w packages/rapidhash-js run build

      - run: npm -w packages/benchmark run compile

      - run: npm -w packages/benchmark run bench:bytes
