name: Publish

on:
  workflow_dispatch:
    inputs:
      target_element:
        description: 'Semver element will be incremented'
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6.0.0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm (Ensure npm 11.5.1 or later is installed)
        run: npm install -g npm@latest

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Bump version
        run: |
          npm version ${{ inputs.target_element }} \
            --include-workspace-root \
            --no-git-tag-version \
            -w packages/rapidhash-js

      - name: Get version string
        id: get-version-string
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Commit and tag
        run: |
          git add \
            package.json \
            package-lock.json \
            packages/rapidhash-js/package.json
          git commit -m "v${{ steps.get-version-string.outputs.version }}"
          git tag "v${{ steps.get-version-string.outputs.version }}"

      - name: Build
        run: |
          npm ci
          npm -w packages/rapidhash-js run build
          cp README.md LICENSE CHANGELOG.md packages/rapidhash-js/

      - name: Publish
        run: npm -w packages/rapidhash-js publish --provenance --access public

      - name: Push commits and tag
        run: |
          git push
          git push origin "v${{ steps.get-version-string.outputs.version }}"

  purge-camo-cache:
    needs: publish
    uses: ./.github/workflows/purge-camo-cache.yaml
