name: Test

on: push

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [20, 22, 24]

    steps:
      - uses: actions/checkout@v6.0.0

      - uses: actions/setup-node@v6.0.0
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run test

  test-bun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.0

      - uses: oven-sh/setup-bun@v2.0.2

      - run: bun install

      - run: bun run test
