name: Test

on: push

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [22, 24, 26]

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: ${{ matrix.version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run test

  test-bun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7.0.1

      - uses: oven-sh/setup-bun@v2.2.0

      - run: bun install

      - run: bun run test
